name: GitHub Actions
run-name: ${{ github.actor }} is pushing his code
on: 
  push:
    branches:
      - main
    tags:
      - v[12].[0-9]+.[0-9]+

  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - name: Run npm audit 
        run: npm audit --json > audit.json || echo "No vulnerabilities found."
      - name: Check vulnerabilities
        run: |
          VULNERABILITIES=$(cat audit.json | jq -r '.vulnerabilities.total')
          if [ "$VULNERABILITIES" -gt 0 ]; then
            echo "Vulnerabilities found!"
            echo "::set-output name=vulnerabilities::true"
          else
            echo "No vulnerabilities found."
            echo "::set-output name=vulnerabilities::false"
          fi

  build:
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: |
          echo $PWD
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-code
          path: /home/runner/work/git-ci-cd-test/
  
  deploy:
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-code

      # Étapes de déploiement de votre API vers le VPS DigitalOcean
      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy files via SCP
        run: |
          scp -i key.pem -r compiled-code ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/var/www

     # - name: Copy files to VPS
     #   run: |
     #     scp -r compiled-code ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/var/www

      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PWD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www
            ls
